package br.gov.rn.saogoncalo.sisaafim.enums;

public enum TipoImovel {
    APARTAMENTO,
    EDIFICIO_COMERCIAL,
    CASA_ISOLADA,
    CASA_GERMINADA_1L,
    CASA_GERMINADA_2L,
    LOJA_GALERIA_SHOPPING,
    CLUBE_CINEMA,
    GINASIO,
    EDIFICACAO_ESPECIAL,
    EDUCACAO,
    TEMPLO,
    GARAGEM_DEPOSITO,
    HOTEL_POUSADA_MOTEL,
    GALPAO,
    INDUSTRIA_FABRICA,
    HOSPITAL_CLINICA,
    SUBSTACAO,
    POSTO_DE_COMBUSTIVEL,
    INSTITUICAO_FINANCEIRA,
    TELHEIRO_EDIFICACAO_PRECARIA,
    CONTRUCAO_PRECARIA,
    TERRENO;
}
